version: '3.9'
services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
volumes:
  postgres:
